'use client';

import { useState, useEffect } from 'react';
import { Button, Input } from '@/components/ui';
import { YouTubePlayer } from '@/components/YoutubePlayer';
import { SummaryCard } from '@/components/SummaryCard';
import { extractVideoId } from '@/lib/helpers';

export default function LandingBody() {
  const [url, setUrl] = useState('');
  const [videoId, setVideoId] = useState('');
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState<any>(null);
  const [fullTranscript, setFullTranscript] = useState<string>('');
  const [title, setTitle] = useState<string>('');

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const videoURL = e.target.value;
    setUrl(videoURL);
    const extracted = extractVideoId(videoURL) as string;
    setVideoId(extracted);
  };

  // Client-side transcript extraction via DOM scraping after player loads
  useEffect(() => {
    if (!videoId) {
      setFullTranscript('');
      setTitle('');
      setSummary(null);
      return;
    }

    const extract = async () => {
      setLoading(true);
      try {
        // 1. Click "...more" to expand description (textContent often "...more")
        const moreButton = Array.from(document.querySelectorAll('button, yt-button-shape button')).find(
          (btn: any) => btn.textContent?.trim() === '...more'
        ) as HTMLElement;

        if (moreButton) moreButton.click();

        await new Promise(r => setTimeout(r, 1000)); // Wait for expansion

        // 2. Click "Show transcript" – reliable via aria-label
        const transcriptButton = document.querySelector('[aria-label="Show transcript"]') as HTMLElement;

        if (!transcriptButton) {
          throw new Error('No captions available or "Show transcript" button not found');
        }
        transcriptButton.click();

        await new Promise(r => setTimeout(r, 2000)); // Wait for panel to load

        // 3. Poll for transcript segments
        const poll = () => {
          const segments = document.querySelectorAll('ytd-transcript-segment-renderer');
          if (segments.length > 0) {
            const lines: { time: number; text: string }[] = [];

            segments.forEach((seg: any) => {
              const timeEl = seg.querySelector('.cue-group-start-offset') || seg.querySelector('time');
              const textEl = seg.querySelector('.cue');

              if (timeEl && textEl) {
                const timeText = timeEl.textContent?.trim() || '0:00';
                const [mins, secs] = timeText.split(':').map(Number);
                const start = mins * 60 + secs;

                const text = textEl.textContent?.trim() || '';
                lines.push({ time: start, text });
              }
            });

            if (lines.length === 0) throw new Error('Transcript loaded but no text found');

            const transcriptText = lines.map(l => l.text).join(' ');
            console.log(transcriptText);
            setFullTranscript(transcriptText);

            // Extract title
            const titleEl = document.querySelector('h1.ytd-watch-metadata yt-formatted-string, h1.title');
            setTitle(titleEl?.textContent?.trim() || 'Unknown Title');

            // TODO: Replace with real summary generation
            // For now, mock a simple summary
            const mockSummary = {
              title: titleEl?.textContent?.trim() || 'Video Title',
              summary: `Key points extracted from transcript:\n\n${transcriptText.substring(0, 500)}...\n\n(Full summary would be generated by AI here)`,
            };
            setSummary(mockSummary);
          } else {
            setTimeout(poll, 1000);
          }
        };

        poll();
      } catch (err: any) {
        console.error(err);
        setSummary({ error: err.message || 'Failed to extract transcript – video may lack captions' });
      } finally {
        setLoading(false);
      }
    };

    // Delay start until player and DOM are ready
    const timer = setTimeout(extract, 3000);
    return () => clearTimeout(timer);
  }, [videoId]);

  return (
    <main className='min-h-screen p-4'>
      <div className='mx-auto max-w-4xl'>
        <h1 className='mb-8 text-center text-3xl font-bold'>SummaTube</h1>

        {/* URL Input */}
        <div className='mb-8 flex gap-2'>
          <Input
            type='url'
            placeholder='Paste YouTube URL here'
            value={url}
            onChange={handleInputChange}
            className='flex-1'
          />
          <Button disabled={loading || !videoId}>
            {loading ? 'Processing...' : 'Load & Summarize'}
          </Button>
        </div>

        {/* Video and Summary */}
        {videoId && (
          <div className='grid gap-8 lg:grid-cols-2'>
            {/* Video Player */}
            <div className='aspect-video'>
              <YouTubePlayer videoId={videoId} onReady={() => {}} />
            </div>

            {/* Summary */}
            <div>
              <SummaryCard
                summary={summary}
                loading={loading}
                video_id={videoId}
              />
            </div>
          </div>
        )}
      </div>
    </main>
  );
}